export const Users = [
  { id: 1, profilePicture: 'assets/person/1.jpeg', username: 'Ishaq' },
  { id: 2, profilePicture: 'assets/person/2.jpeg', username: 'Nawaz' },
  { id: 3, profilePicture: 'assets/person/3.jpeg', username: 'Arman' },
  { id: 4, profilePicture: 'assets/person/4.jpeg', username: 'Ibrahim' },
  { id: 5, profilePicture: 'assets/person/4.jpeg', username: 'Rziwan' },
  { id: 6, profilePicture: 'assets/person/4.jpeg', username: 'Ismail' },
  { id: 7, profilePicture: 'assets/person/4.jpeg', username: 'Rana' },
  { id: 8, profilePicture: 'assets/person/4.jpeg', username: 'Nida' },
  { id: 9, profilePicture: 'assets/person/4.jpeg', username: 'fatima' },
  { id: 10, profilePicture: 'assets/person/4.jpeg', username: 'Hira' },
];

export const Posts = [
  {
    id: 1,
    dsc: 'Love all friends',
    photo: 'assets/post/1.jpeg',
    date: '5 minute ag0',
    userId: 1,
    like: 9,
    comment: 32,
  },
  {
    id: 2,
    photo: 'assets/post/2.jpeg',
    date: '2 minute ag0',
    userId: 2,
    like: 8,
    comment: 2,
  },
  {
    id: 3,
    photo: 'assets/post/3.jpeg',
    date: '5 minute ag0',
    userId: 3,
    like: 9,
    comment: 312,
  },
  {
    id: 4,
    dsc: 'Nature ',
    photo: 'assets/post/4.jpeg',
    date: '10 minute ag0',
    userId: 4,
    like: 99,
    comment: 232,
  },
  {
    id: 5,
    dsc: 'Poetry',
    photo: 'assets/post/5.jpeg',
    date: '51 minute ag0',
    userId: 5,
    like: 92,
    comment: 2,
  },
  {
    id: 6,
    dsc: 'Love all friends',
    photo: 'assets/post/6.jpeg',
    date: '20 minute ag0',
    userId: 6,
    like: 19,
    comment: 3,
  },
  {
    id: 7,
    photo: 'assets/post/7.jpeg',
    date: '25 minute ag0',
    userId: 7,
    like: 119,
    comment: 332,
  },
];
